-- schema.sql
-- Cumulative reference schema, generated by concatenating all applied
-- migrations in order. This file is for reference and fresh local setup
-- only — the migrations in migrations/ are the source of truth.
-- Regenerate after adding a new migration.

-- ==== 000_enable_extensions.sql ====
-- 000_enable_extensions.sql
-- Enables PostgreSQL extensions required by later migrations.
-- pgcrypto provides gen_random_uuid(), used as the default for all
-- surrogate primary keys in this schema.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==== 001_create_roles.sql ====
-- 001_create_roles.sql
-- Reference table of the four hierarchy tiers plus Super Admin.
-- hierarchy_level encodes ordering: 0 = Super Admin ... 4 = Player.
-- This table only stores role identity; enforcement of "who may
-- create/act on whom" (BR-1 to BR-9) belongs to the service layer.

CREATE TABLE roles (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            VARCHAR(30) NOT NULL,
    hierarchy_level SMALLINT NOT NULL,
    description     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_roles_name UNIQUE (name),
    CONSTRAINT uq_roles_hierarchy_level UNIQUE (hierarchy_level),
    CONSTRAINT chk_roles_hierarchy_level_range CHECK (hierarchy_level BETWEEN 0 AND 4)
);

COMMENT ON TABLE roles IS 'Fixed set of hierarchy tiers: Super Admin (0), Level 1 (1), Level 2 (2), Level 3 (3), Player (4).';

-- ==== 002_create_users.sql ====
-- 002_create_users.sql
-- Core account table for every role. created_by is a self-referencing
-- foreign key modeling the hierarchy (BR-1 to BR-9): every user except
-- the initial Super Admin has exactly one creator, one level above them.
-- Enforcing "creator must be exactly one tier above" is a business rule
-- (service layer), not a database constraint.
--
-- password_hash stores the hashed credential; no hashing logic is
-- implemented in this migration or its seed data (see docs/06_PROJECT_STATUS.md
-- — authentication is a later milestone).

CREATE TABLE users (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    role_id       UUID NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    created_by    UUID REFERENCES users(id) ON DELETE RESTRICT,
    username      VARCHAR(50) NOT NULL,
    email         VARCHAR(255),
    password_hash TEXT NOT NULL,
    status        VARCHAR(10) NOT NULL DEFAULT 'active',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_status CHECK (status IN ('active', 'frozen')),
    CONSTRAINT chk_users_not_own_creator CHECK (created_by IS NULL OR created_by <> id)
);

CREATE INDEX idx_users_created_by ON users (created_by);
CREATE INDEX idx_users_role_id ON users (role_id);

COMMENT ON TABLE users IS 'All accounts across all roles. created_by models the hierarchy; NULL only for the initial Super Admin.';
COMMENT ON COLUMN users.password_hash IS 'Placeholder column only in this milestone — hashing is implemented in the authentication milestone.';

-- ==== 003_create_user_profiles.sql ====
-- 003_create_user_profiles.sql
-- Optional profile data, separated from the core auth-bearing users
-- table so profile edits never touch authentication-critical columns.

CREATE TABLE user_profiles (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    full_name    VARCHAR(100),
    display_name VARCHAR(50),
    avatar_url   TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_user_profiles_user_id UNIQUE (user_id)
);

COMMENT ON TABLE user_profiles IS 'One-to-one profile data per user, separate from authentication fields on users.';

-- ==== 004_create_wallets.sql ====
-- 004_create_wallets.sql
-- One virtual point balance per user (FR-3.1). Points have no
-- real-world monetary value (BR-16) — balance is a plain integer
-- count, never a currency amount.
-- BR-12: no account may ever hold a negative balance, enforced here
-- with a CHECK constraint at the database level as a hard backstop
-- in addition to service-layer enforcement.

CREATE TABLE wallets (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    balance    BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_wallets_user_id UNIQUE (user_id),
    CONSTRAINT chk_wallets_balance_non_negative CHECK (balance >= 0)
);

COMMENT ON TABLE wallets IS 'Virtual point balance per user. Points are non-monetary (BR-16); balance must never go negative (BR-12).';

-- ==== 005_create_wallet_transactions.sql ====
-- 005_create_wallet_transactions.sql
-- Immutable record of every downward point transfer between a user
-- and a direct child (BR-10, BR-11, BR-14). This table records
-- hierarchy transfers only; points consumed for game access are
-- recorded on game_sessions instead, since Players cannot transfer
-- points onward (BR-15).

CREATE TABLE wallet_transactions (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sender_id               UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    recipient_id            UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    amount                  BIGINT NOT NULL,
    sender_balance_after    BIGINT NOT NULL,
    recipient_balance_after BIGINT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_wallet_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT chk_wallet_transactions_sender_balance_non_negative CHECK (sender_balance_after >= 0),
    CONSTRAINT chk_wallet_transactions_recipient_balance_non_negative CHECK (recipient_balance_after >= 0),
    CONSTRAINT chk_wallet_transactions_no_self_transfer CHECK (sender_id <> recipient_id)
);

CREATE INDEX idx_wallet_transactions_sender_id ON wallet_transactions (sender_id);
CREATE INDEX idx_wallet_transactions_recipient_id ON wallet_transactions (recipient_id);

COMMENT ON TABLE wallet_transactions IS 'Immutable ledger of downward point transfers through the hierarchy (BR-10, BR-11, BR-14). Never updated or deleted.';

-- ==== 006_create_game_categories.sql ====
-- 006_create_game_categories.sql
-- Simple grouping for the arcade game catalog (e.g. "Puzzle", "Arcade",
-- "Card"). Created before games so games can reference it.

CREATE TABLE game_categories (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(50) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_game_categories_name UNIQUE (name)
);

COMMENT ON TABLE game_categories IS 'Catalog grouping for arcade games.';

-- ==== 007_create_games.sql ====
-- 007_create_games.sql
-- Catalog of available simple arcade games and their point cost
-- (FR-4.1). These are self-contained games — this schema does not
-- model odds, wagers, or bet outcomes of any kind.

CREATE TABLE games (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id UUID REFERENCES game_categories(id) ON DELETE SET NULL,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    point_cost  INTEGER NOT NULL DEFAULT 0,
    is_active   BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_games_name UNIQUE (name),
    CONSTRAINT chk_games_point_cost_non_negative CHECK (point_cost >= 0)
);

CREATE INDEX idx_games_category_id ON games (category_id);

COMMENT ON TABLE games IS 'Catalog of simple arcade games and their point cost to play (FR-4.1).';

-- ==== 008_create_game_sessions.sql ====
-- 008_create_game_sessions.sql
-- Each instance of a Player accessing a game (BR-20, BR-21, BR-22).
-- points_spent is recorded on the session itself (not as a
-- wallet_transactions row), since game-access consumption is
-- distinct from a hierarchy transfer (BR-15).

CREATE TABLE game_sessions (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    game_id       UUID NOT NULL REFERENCES games(id) ON DELETE RESTRICT,
    points_spent  INTEGER NOT NULL,
    score         INTEGER,
    status        VARCHAR(15) NOT NULL DEFAULT 'in_progress',
    started_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at  TIMESTAMPTZ,

    CONSTRAINT chk_game_sessions_points_spent_non_negative CHECK (points_spent >= 0),
    CONSTRAINT chk_game_sessions_status CHECK (status IN ('in_progress', 'completed', 'abandoned')),
    CONSTRAINT chk_game_sessions_completed_at_after_started CHECK (completed_at IS NULL OR completed_at >= started_at)
);

CREATE INDEX idx_game_sessions_user_id ON game_sessions (user_id);
CREATE INDEX idx_game_sessions_game_id ON game_sessions (game_id);

COMMENT ON TABLE game_sessions IS 'Each Player game-access instance, points spent, and resulting score (BR-20 to BR-22).';

-- ==== 009_create_notifications.sql ====
-- 009_create_notifications.sql
-- Per-user notification records for significant events (BR-28):
-- account creation, point transfers, password changes, status
-- updates, and game completion.

CREATE TABLE notifications (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type       VARCHAR(50) NOT NULL,
    message    TEXT NOT NULL,
    is_read    BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_user_id ON notifications (user_id);
CREATE INDEX idx_notifications_user_id_is_read ON notifications (user_id, is_read);

COMMENT ON TABLE notifications IS 'Per-user notifications for account, wallet, and game events (BR-28).';

-- ==== 010_create_audit_logs.sql ====
-- 010_create_audit_logs.sql
-- Immutable log of every sensitive action across the system
-- (BR-25, BR-26, BR-27). No UPDATE or DELETE should ever be issued
-- against this table; that guarantee is enforced by application-level
-- discipline (services never call update/delete repository methods
-- against this table) rather than a database trigger, to keep this
-- migration free of business logic per CLAUDE.md.

CREATE TABLE audit_logs (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_id    UUID REFERENCES users(id) ON DELETE SET NULL,
    action      VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50),
    entity_id   UUID,
    metadata    JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_actor_id ON audit_logs (actor_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);

COMMENT ON TABLE audit_logs IS 'Immutable action log (BR-25 to BR-27). actor_id may be NULL if the acting account is later deleted; the log entry itself is retained.';

-- ==== 011_create_system_settings.sql ====
-- 011_create_system_settings.sql
-- Simple key-value store for platform-wide configuration
-- (e.g. maintenance mode, default point costs) that admins may
-- adjust without a code deployment.

CREATE TABLE system_settings (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key         VARCHAR(100) NOT NULL,
    value       TEXT,
    description TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_system_settings_key UNIQUE (key)
);

COMMENT ON TABLE system_settings IS 'Key-value platform configuration, editable by administrators without a code deployment.';

